# Generated by Django 4.1.7 on 2023-03-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='write',
            new_name='writer',
        ),
    ]
